name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - SiraLocalizer/**
    - SiraLocalizer.sln

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    # using MSBuild since ILRepack.Lib.MSBuild (and equivalent packages) use an older version of ILRepack that doesn't work on .NET 8 and above
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@main
      with:
        access-token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        manifest: ${{ github.workspace }}\SiraLocalizer\manifest.json

    - name: Build Release
      id: build-release
      run: |
        msbuild ${{ github.workspace }}\SiraLocalizer\SiraLocalizer.csproj -p:Configuration=Release -t:restore
        msbuild ${{ github.workspace }}\SiraLocalizer\SiraLocalizer.csproj -p:Configuration=Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
